targets:
  container_A:
    frame_id: base_link
    position: {x: 0.3, y: 0.2, z: 0.15}
    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  scale:
    frame_id: base_link
    position:
      x: 0.27924886431389628
      y: 2.4369072076870182e-05
      z: 0.43011920528478864
    orientation:
      x: 9.2654253295640644e-05
      y: -1.5204153481965351e-05
      z: 4.3634848255700872e-05
      w: 0.99999999464001155
  boxB:
    frame_id: base_link
    position:
      x: 0.23447880506217758
      y: 0.052203261718902209
      z: 0.25913493420867406
    orientation:
      x: 0.037889022517906677
      y: 0.081518068675841243
      z: 0.10673694541517918
      w: 0.9902153558370197
  boxB_qr:
    frame_id: base_link
    position:
      x: 0.17729448926018768
      y: 0.15783715779199542
      z: 0.25635414848404225
    orientation:
      x: -0.073840685696193786
      y: 0.054283473671513392
      z: 0.41437800663711383
      w: 0.90547872710380228
  test2:
    frame_id: base_link
    position:
      x: 0.13823187320817326
      y: 0.11432269325178894
      z: 0.38641839417038115
    orientation:
      x: 0.068670673031351062
      y: -0.20968784014171582
      z: 0.35755523242586135
      w: 0.90745225997129553
  home:
    frame_id: base_link
    position:
      x: 0.27924886431389628
      y: 2.4369072076870182e-05
      z: 0.43011920528478864
    orientation:
      x: 9.2654253295640644e-05
      y: -1.5204153481965351e-05
      z: 4.3634848255700872e-05
      w: 0.99999999464001155
  s1:
    frame_id: base_link
    position:
      x: 0.36654354662353783
      y: -0.040097666315031123
      z: 0.40880431208388546
    orientation:
      x: 0.068495643617754093
      y: 0.48292704327154168
      z: -0.0040720924125119285
      w: 0.87296806112582381
  s2:
    frame_id: base_link
    position:
      x: 0.40421496318394473
      y: -0.023300421975441701
      z: 0.29164662761616028
    orientation:
      x: 0.066931784466306377
      y: 0.34617339158637739
      z: -0.00056973514905562183
      w: 0.93577977889437236
  s3:
    frame_id: base_link
    position:
      x: 0.43656620821771558
      y: -0.027342082603285411
      z: 0.25828540795062049
    orientation:
      x: 0.034325385069494195
      y: 0.26424587202080757
      z: -0.020379453995028367
      w: 0.96362885226349382
  s4:
    frame_id: base_link
    position:
      x: 0.41261810257070514
      y: -0.026652371771986552
      z: 0.24841964492742605
    orientation:
      x: 0.036382897827307178
      y: -0.20046091030483806
      z: -0.054523681985520503
      w: 0.97750645843809403
  boxA:
    frame_id: base_link
    position:
      x: 0.36051267833610018
      y: -0.20910528007727419
      z: 0.32488280810595682
    orientation:
      x: 0.041103811550891094
      y: 0.05439850860106038
      z: -0.25891157278337434
      w: 0.96349160682219159
  boxA_qr:
    frame_id: base_link
    position:
      x: 0.33398833259036376
      y: 0.15985374833554045
      z: 0.25357739198535179
    orientation:
      x: -0.017742631338030553
      y: 0.46196229974169778
      z: 0.14734205719460311
      w: 0.87439484835640857
  gibberland:
    frame_id: base_link
    position:
      x: 0.29336429685372839
      y: -0.0042180206527874901
      z: 0.183044742055464
    orientation:
      x: 0.024227667309820709
      y: 0.028194643392167148
      z: -0.020343373644420924
      w: 0.99910171122337521
  defaultPosition:
    frame_id: base_link
    position:
      x: 0.42747838927434917
      y: -0.19996945708145444
      z: 0.11999904836280403
    orientation:
      x: -0.00020108572978437986
      y: -0.00012651784546983881
      z: -0.00060098765853328052
      w: 0.99999979118577742
  contA_qr:
    frame_id: base_link
    position:
      x: 0.2403635873805646
      y: 0.11888878574678446
      z: 0.39614877916825453
    orientation:
      x: -0.10599074016067948
      y: 0.23273644660821402
      z: 0.22503688940044131
      w: 0.94019046359200364
  contA:
    frame_id: base_link
    position:
      x: 0.31056308112410136
      y: 0.17764277448663954
      z: 0.23874357495293813
    orientation:
      x: -0.12406723777009424
      y: 0.35977686200247033
      z: 0.24873059457167754
      w: 0.89067447555421397
  contB_qr:
    frame_id: base_link
    position:
      x: 0.20242170772270027
      y: -0.15295492847153816
      z: 0.42380801991296113
    orientation:
      x: 0.027399728102735214
      y: 0.25931662163049946
      z: -0.30868267260189297
      w: 0.91472353871614842
  contB:
    frame_id: base_link
    position:
      x: 0.32046336442874002
      y: -0.19487246896211607
      z: 0.22781544595618705
    orientation:
      x: 0.044717740473193698
      y: 0.32405671715496465
      z: -0.23872161297077349
      w: 0.91433011503195694